import "../../app/globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/Footer";

export const metadata = {
  title: 'Clarington -- About',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-oswald">
        <Header/>
        {children}
        <Footer />
        {/* Add ScrollToTopButton below the Footer */}
      </body>
    </html>
  );
}
